DZ N14: Docker microservices
Otus-DevOps-22-08/SantikaS_microservices pull request #1
Opened 2022-12-10 12:02 UTC by SantikaS

2022-12-17 09:12 UTC, mrgreyves requested changes
Здравствуйте!)
Где т у вас потерялись тесты
Нужно их добавить, так же как вы делали в инфра репозитории
ДЗ возвращаю на доработку

2022-12-18 17:09 UTC, SantikaS commented
Добрый вечер! Да, к микросервисам не подключил проверки..... Ещё подумал странно, что-то проверок нет...

2022-12-19 10:59 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все классно =)

2022-12-19 11:00 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все классно =)

2022-12-19 11:27 UTC, merged